services:
  # --- Infrastructure ---
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    ports: ["5432:5432"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=autohub_auth_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports: ["5672:5672", "15672:15672"]

  # --- Application Services ---
  discovery-server:
    build: ./discovery-server # Correct Path
    container_name: discovery-server
    ports: ["8761:8761"]
    environment: ["SPRING_PROFILES_ACTIVE=docker"]

  api-gateway:
    build: ./api-gateway # Correct Path
    container_name: api-gateway
    ports: ["8080:8080"]
    environment: ["SPRING_PROFILES_ACTIVE=docker"]
    depends_on: [discovery-server]

  auth-service:
    build: ./auth-service # Correct Path
    container_name: auth-service
    ports: ["8090:8090"]
    environment: ["SPRING_PROFILES_ACTIVE=docker"]
    depends_on: [postgres-db, discovery-server]

  product-catalog-service:
    build: ./product-catalog-service # Correct Path
    container_name: product-catalog-service
    ports: ["8081:8081"]
    environment: ["SPRING_PROFILES_ACTIVE=docker"]
    depends_on: [postgres-db, discovery-server]

  inventory-service:
    build: ./inventory-service # Correct Path
    container_name: inventory-service
    ports: ["8082:8082"]
    environment: ["SPRING_PROFILES_ACTIVE=docker"]
    depends_on: [postgres-db, discovery-server]

  order-service:
    build: ./order-service # Correct Path
    container_name: order-service
    ports: ["8083:8083"]
    environment: ["SPRING_PROFILES_ACTIVE=docker"]
    depends_on: [postgres-db, discovery-server, rabbitmq]

  payment-service:
    build: ./payment-service # Correct Path
    container_name: payment-service
    ports: ["8085:8085"]
    environment: ["SPRING_PROFILES_ACTIVE=docker"]
    depends_on: [postgres-db, discovery-server]

  notification-service:
    build: ./notification-service # Correct Path
    container_name: notification-service
    ports: ["8084:8084"]
    environment: ["SPRING_PROFILES_ACTIVE=docker"]
    depends_on: [discovery-server, rabbitmq]

volumes:
  postgres-data: