# application.yaml for Inventory Service

# Run this service on a new, unique port
server:
  port: 8082

spring:
  application:
    name: inventory-service

  # --- Database Configuration (A SEPARATE DATABASE) ---
  datasource:
    url: jdbc:postgresql://localhost:5432/autohub_inventory_db
    username: postgres
    password: mysecretpassword

  # --- JPA and Flyway ---
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

# --- Eureka Client Configuration ---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka